language: node_js
node_js:
  - "stable"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libc6
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main
